Contactmanagement/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Contactmanagement.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^home/$','contactapp.views.home'),
    url(r'^contact/$','contactapp.views.contactpage'),
    url(r'^add_contact/$','contactapp.views.addcontact'),
    url(r'^display_contact/$','contactapp.views.displaycontact'),
    url(r'^display_contact/(\w)$','contactapp.views.displaycontact_alphabet'),
)

contactapp/models.py
from django.db import models

# Create your models here.


class  Login(models.Model):
    user_id_number=models.CharField(max_length=100) #The user number serves as the number
    password=models.CharField(max_length=100)      #Password for the relevent number

    def __unicode__(self):
        return self.user_id_number




class Contacts1(models.Model):
        contact_first_name=models.CharField(max_length=200)
        contact_second_name=models.CharField(max_length=200)
        contact_number=models.BigIntegerField()
        contact_email_id=models.CharField(max_length=200)

        def __unicode__(self):
             return self.contact_first_name

contactapp/forms.py
from django import forms
from contactapp.models import Login
from contactapp.models import Contacts1



class Login_details(forms.Form):
    user_id_number=forms.CharField(max_length=100,required=True) #The user number serves as the number
    password = forms.CharField(widget=forms.PasswordInput())  #Password for the relevent number

class Contact_add1(forms.ModelForm):
    class Meta:
        model=Contacts1

contactapp/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response,RequestContext
from contactapp.forms import Login_details
from contactapp.models import Login
from contactapp.forms import Contact_add1
from contactapp.models import Contacts1




def home(request):  #Displays the Login page
    form=Login_details(request.POST or None)
    return render_to_response('index.html',locals(),context_instance=RequestContext(request))


def contactpage(request):  #Displays Tthe home page
    form=Login_details(request.POST or None)
    if form.is_valid():
        user_id=form.cleaned_data['user_id_number']
        password=form.cleaned_data['password']
        login_credentials=Login.objects.all()[0]
        if login_credentials.user_id_number == user_id and login_credentials.password == password: #username & password check
            return render_to_response('homepage.html',{})
        else:
            return render_to_response('login_error.html',{})


def addcontact(request):    #addingcontacts
    form= Contact_add1(request.POST or None)
    if form.is_valid():
        save_contact = form.save(commit=False)
        save_contact.save()
    return render_to_response('add_contact.html',locals(),context_instance=RequestContext(request))

def displaycontact(request): #displaying contacts
    contactList = []
    contactDetails = []
    for contact in Contacts1.objects.all():
        contactDetails = [contact.contact_first_name,contact.contact_second_name,  contact.contact_number,contact.contact_email_id ]
        print contactDetails
        contactList.append(contactDetails)
        contactList.sort()
    return render_to_response('display_contact.html',{'users':contactList})

def displaycontact_alphabet(request,letter):  #pagenated display
    uppercase_letter=letter.upper()
    contactList = []
    contactDetails = []
    for contact in Contacts1.objects.all():
        if letter==contact.contact_first_name[0] or uppercase_letter==contact.contact_first_name[0]:
         contactDetails = [contact.contact_first_name,contact.contact_second_name,  contact.contact_number,contact.contact_email_id ]
         print contactDetails
         contactList.append(contactDetails)
         contactList.sort()
    return render_to_response('display_contact.html',{'users':contactList})

templates/add_contact.html
<!DOCTYPE html>
<html>
<head>
    <title>Add Contacts</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
  <script src="//code.jquery.com/jquery-1.9.1.js"></script>
  <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
  <script>
  $(function() {
  
    // Setup form validation on the #register-form element
    $("#add_contact_form").validate({
    
        // Specify the validation rules
        rules: {
            contact_first_name: {required:true,
                                 customvalidation: true},
            contact_number: {required: false,
                             number: true,
                             rangelength : [10, 10]},
            contact_email_id :{required: false,
                               email: true}

        },
        
        // Specify the validation error messages
        messages: {
            contact_first_name: "Please enter a First Name",
            contact_number: "Please enter a Contact Number",
            contact_email_id: "Please enter a Valid Email ID"

        },
        
        submitHandler: function(form) {
            form.submit();
        }
    });
    $.validator.addMethod("customvalidation",
              function(value, element) {
                  return /^[A-Za-z\d=#$%@_ -]+$/.test(value);
              },
              "Sorry, no special characters allowed"
    );
  });
  
  </script>

</head>
<body>
    <div class="page-header">
 	 <center><h1>Contact management System</h1></center>
    </div>
    <div class="page-header">
         <center><h4>Add Contact</h4></center>
    </div>

    <br>
<div class="col-xs-offset-4">
	<form role="form" action="" method="post" id="add_contact_form"> {% csrf_token %}
          <div class="col-sm-7"> 
           <p><label for="id_contact_first_name" class="row-sm-7 control-label">First Name</label>
              <input type="text" class="form-control" name= "contact_first_name"  id="id_contact_first_name" placeholder="Enter First Name">
	   </p>
          </div>
          <div class="col-sm-7">
           <p><label for="id_contact_second_name" class="row-sm-2 control-label">Second Name</label>
              <input type="text" class="form-control" name="contact_second_name" id="id_contact_second_name" placeholder="Enter Second Name">
           </p>
          </div>
          <div class="col-sm-7">
           <p><label for="id_contact_number" class="row-sm-2 control-label">Contact Number</label>
              <input type="text" class="form-control" name="contact_number" id="id_contact_number" placeholder="Enter Number">
           </p>
          </div>
	  <div class="col-sm-7">
           <p><label for="id_contact_email_id" class="row-sm-2 control-label">Email ID</label>
              <input type="text" class="form-control" name="contact_email_id" id="id_contact_email_id" placeholder="Enter Email ID">
           </p>
           <button type="submit" class="btn btn-default">Add</button>
          <a href="/display_contact/" style="text-decoration:none">
              <button type="button" class="btn btn-default" >Display Contacts</button>
          </a>
         </div>   
       </form>

</div>


<!-- Latest compiled and minified JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/display_contact.html
<!DOCTYPE html>
<html>
<head>
    <title>Display Contacts</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
</head>
<body>
<div class="page-header">
  <center><h1>Contact management System</h1></center>
</div>
<div class="page-header">
  <center><h4>Contacts Display</h4></center>
</div>


<center>
<ul class="pagination">
  <li><a href="#">&laquo;</a></li>
  <li><a href="a">A</a></li><li><a href="b">B</a></li><li><a href="c">C</a></li><li><a href="d">D</a></li><li><a href="e">E</a></li>
  <li><a href="f">F</a></li><li><a href="g">G</a></li><li><a href="h">H</a></li><li><li><a href="i">I</a></li><li><a href="j">J</a></li>
  <li><a href="k">K</a></li><li><a href="l">L</a></li><li><a href="m">M</a></li><li><a href="n">N</a></li><li><a href="o">O</a></li>
  <li><a href="p">P</a></li><li><a href="q">Q</a></li><li><a href="r">R</a></li><li><a href="s">S</a></li><li><a href="t">T</a></li>
  <li><a href="u">U</a></li><li><a href="v">V</a></li><li><a href="w">W</a></li><li><a href="x">X</a></li><li><a href="y">Y</a></li>
  <li><a href="Z">Z</a></li>
  <li><a href="#">&raquo;</a></li>
</ul></center>
{% if users %}
{% for contact_name,contact_second_name,contact_number,contact_email in users %}
    <pre>First  Name  : {{ contact_name }}<br>Second Name  : {{ contact_second_name }}
Contact No.  : {{ contact_number }}<br>Email ID     : {{ contact_email }}</pre><br>
{% endfor %}
{% else %}
 <pre><center>No Contacts to Display</center></pre>
{% endif %}
<center>
<ul class="pagination">
  <li><a href="#">&laquo;</a></li>
  <li><a href="a">A</a></li><li><a href="b">B</a></li><li><a href="c">C</a></li><li><a href="d">D</a></li><li><a href="e">E</a></li>
  <li><a href="f">F</a></li><li><a href="g">G</a></li><li><a href="h">H</a></li><li><li><a href="i">I</a></li><li><a href="j">J</a></li>
  <li><a href="k">K</a></li><li><a href="l">L</a></li><li><a href="m">M</a></li><li><a href="n">N</a></li><li><a href="o">O</a></li>
  <li><a href="p">P</a></li><li><a href="q">Q</a></li><li><a href="r">R</a></li><li><a href="s">S</a></li><li><a href="t">T</a></li>
  <li><a href="u">U</a></li><li><a href="v">V</a></li><li><a href="w">W</a></li><li><a href="x">X</a></li><li><a href="y">Y</a></li>
  <li><a href="Z">Z</a></li>
  <li><a href="#">&raquo;</a></li>
</ul></center>


<!-- Latest compiled and minified JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html>
<head>
    <title>Welcome to Contact management System</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
</head>

<body>
  <div class="page-header">
     <center><h1>Contact management System</h1></center>
  </div>
 <br><br><br><br> 
 
   
 <div class="col-xs-offset-4">
	 <div class="col-sm-7"> 
		<a href="/add_contact/" style="text-decoration:none">
	            <button type="button" class="btn btn-primary btn-lg btn-block" >Add New Contact</button>
		</a>
		<br>
		<a href="/display_contact/" style="text-decoration:none">
	            <button type="button" class="btn btn-default btn-lg btn-block">Display All Contacts</button>
		</a>
	 </div>
 </div>  

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>

<head>
    <title>Contact Management System</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
  <script src="//code.jquery.com/jquery-1.9.1.js"></script>
  <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
  <script>
  $(function() {
  
    // Setup form validation on the #register-form element
    $("#sign_in_form").validate({
    
        // Specify the validation rules
        rules: {
            user_id_number: "required",
            password: "required"
            
        },
        
        // Specify the validation error messages
        messages: {
            user_id_number: "Please enter a Username/Number",
            password: "Please enter a Password"
        },
        
        submitHandler: function(form) {
            form.submit();
        }
    });

  });
  
  </script>
</head>
<body>

<div class="page-header">
  <center><h1>Contact management System</h1></center>
</div>
 <br><br><br><br> 
 <div class="col-xs-offset-4">
	<form role="form" action="/contact/" method="post" id="sign_in_form"> {% csrf_token %}
              <div class="col-sm-7">  <!--{{ form.as_p }} -->
               <p><label for="id_user_id_number" class="row-sm-7 control-label">Username/Number</label>
               <input type="text" class="form-control" name= "user_id_number"  id="id_user_id_number" placeholder="Enter Username/Number"></p>
              </div>
              <div class="col-sm-7">
               <p><label for="id_password" class="row-sm-2 control-label">Password</label>
               <input type="password" class="form-control" name="password" id="id_password" placeholder="Password"></p>
               <button type="submit" class="btn btn-default">Submit</button> 
              </div>
             
       </form>
 </div>

<!-- Latest compiled and minified JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/login_error.html
<!DOCTYPE html>
<html>
<head>
    <title>Login Error</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
</head>
<body>
<div class="page-header">
  <center><h1>Contact management System</h1></center>
</div>
 <br><br><br><br> 
 <div class="col-xs-offset-5">
   <div class="col-xs-4">
    <div class="alert alert-danger"><a href="/home/" class="alert-link"><center>Invalid Username/Password </center></a></div>
   </div>  
 </div>

<!-- Latest compiled and minified JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</body>
</html>